ProfiledSubsystemPID for Arm
gwhs/2024v2 pull request #22
Opened 2024-02-19 21:56 UTC by ThirstyCorgi

-Deleted experimental code and old code
-Fixed wrap around issue with Arm , prevents overspinning which could cause the wires to tear
-Moved Arm Constants to Arm Subsystem
-Added some new commands (SpinAndSwing and SpinToArmAngle)
-No longer using MagicMotion for Arm, instead using ProfiledSubsystemPID

2024-02-19 21:58 UTC, ThirstyCorgi commented on src/main/java/frc/robot/subsystems/ArmSubsystem.java
> +    public static final int AMP_ANGLE = 0;
These six angles have not been tried yet, so we left them at 0 for now. Will test when we get robot once again.

2024-02-19 21:59 UTC, ThirstyCorgi commented on src/main/java/frc/robot/subsystems/ArmSubsystem.java
> +  private DutyCycleEncoder m_encoder;
Changed encoder from relative to absolute.

2024-02-19 21:59 UTC, ThirstyCorgi commented on src/main/java/frc/robot/subsystems/ArmSubsystem.java
> +    Shuffleboard.getTab("Arm").addDouble("Encoder Angle", ()->encoderGetAngle()).withWidget(BuiltInWidgets.kGraph)
Shows shuffleboard values

2024-02-19 22:02 UTC, ThirstyCorgi commented on src/main/java/frc/robot/subsystems/ArmSubsystem.java
> +  double calculatedAng = angle - Arm.ENCODER_OFFSET;
Arm min angle is the minimum angle the arm can go to (45 degrees); this is around the angle needed for intake.

2024-02-19 22:07 UTC, ThirstyCorgi commented on src/main/java/frc/robot/testcontainers/ArmContainer.java
> +        m_driverController.a().onTrue(Commands.runOnce(() -> {
These commands and the ones below use the arm constants, which we have yet to set.

2024-02-19 22:11 UTC, ThirstyCorgi commented on src/main/java/frc/robot/subsystems/ArmSubsystem.java
> + {
Uses encoder offset since 0 on the encoder is not directly downwards.

2024-02-19 22:22 UTC, ThirstyCorgi commented on src/main/java/frc/robot/subsystems/ArmSubsystem.java
> +    //Comment out for testing purposes
Used for profiledPIDs

2024-02-19 22:30 UTC, ThirstyCorgi reviewed
Commented on changes

2024-02-20 04:35 UTC, RobertTheBlair requested changes
Looks great in general - a few things we should discuss with Team-Intake, or otherwise clean up.

2024-02-20 04:35 UTC, RobertTheBlair commented on src/main/java/frc/robot/Constants.java
>    public static final class IntakeConstants {
We should ask @kctyy and @char-ly1 (?I think?) to review the changes made in Intake classes.

2024-02-20 04:35 UTC, RobertTheBlair commented on src/main/java/frc/robot/Robot.java
> +  public static final String container = ARM;
Let's revert this before we merge to DRIVE, so we don't create merge conflicts

2024-02-20 04:35 UTC, RobertTheBlair commented on src/main/java/frc/robot/commands/Arm/SpinAndSwing.java
> +        Commands.waitSeconds(.5),
Maybe SpinNoteContainerMotor can run until it detects it gets up to speed, by checking if the RPMs are stabilized or above a min value.  Then we don't need to guess how many seconds - it just goes when ready

2024-02-20 04:35 UTC, RobertTheBlair commented on src/main/java/frc/robot/commands/Arm/SpinArmPID.java
> +public class SpinArmPID extends PIDCommand {
Consider adding a comment that we are not using this one at the moment.

2024-02-20 04:35 UTC, RobertTheBlair commented on src/main/java/frc/robot/commands/Arm/SpinToArmAngle.java
> +    System.out.println("hello");
Print statements like this should be removed if they are not helpful, or provide more context.
Such as
`"SpinToArmAngle: initialize.  angle=" + angle`

2024-02-20 04:35 UTC, RobertTheBlair commented on src/main/java/frc/robot/commands/Arm/SwingBackServo.java
> +    return Math.abs(motorAng) < .001;
I suspect this tolerance is too small, and might not end the command in a reasonable time.

2024-02-20 04:35 UTC, RobertTheBlair commented on src/main/java/frc/robot/commands/Arm/SwingForwardServo.java
> +    return Math.abs(motorAng - 180) < .001;
Same here

2024-02-20 04:35 UTC, RobertTheBlair commented on src/main/java/frc/robot/testcontainers/IntakeContainer.java
> +        final PIDController intakeController = new PIDController(.01, .0001, .0);
More changes to the shared code - let's make sure we don't make changes in the other subsystems without discussion.

2024-02-23 01:57 UTC, Chvoong24 approved these changes
good n ough

2024-02-25 01:22 UTC, RobertTheBlair approved these changes
Looks great, looking forward to more testing

2024-02-25 01:23 UTC, merged