April tag
gwhs/2024v2 pull request #7
Opened 2024-01-21 01:00 UTC by wilsomc

2024-01-23 01:37 UTC, RobertTheBlair requested changes
A few changes are needed - once we have the drivetrain working in vision robot, restore the name in DriveContainer, and add the swerve subsystem to VisionContainer

2024-01-23 01:37 UTC, RobertTheBlair commented on src/main/java/frc/robot/Constants.java
> +  public static final class LimeLightConstants {
Might want to put the limelight constants in a different file.  They will vary by which robot is being used,

2024-01-23 01:37 UTC, RobertTheBlair commented on src/main/java/frc/robot/subsystems/LimeVision/LimeLightSub.java
> +    if (getTx() < 0.5 && getTx() > -0.5)
This testing code needs to be removed before we merge.

2024-01-23 01:37 UTC, RobertTheBlair commented on src/main/java/frc/robot/subsystems/LimeVision/PIDMove.java
> +  public PIDMove(SwerveSubsystem swerveSystem, LimeLightSub limeLightSub, double kP, double Ki, double kD, double setPoint) {
This is more like a Command class - where it interacts with two subsystems, and uses them to achieve a goal.
At the moment, it is effectively doing nothing

2024-01-23 01:37 UTC, RobertTheBlair commented on src/main/java/frc/robot/testcontainers/DriveContainer.java
> +    return "swerve/vision";
Discuss with Chris if we should merge this.   I believe we don't want do that yet.

2024-01-23 01:37 UTC, RobertTheBlair commented on src/main/java/frc/robot/testcontainers/VisionContainer.java
> +    private LimeLightSub limeLightSub = new LimeLightSub("limelight");
Once you have debugged the drive setup, you can add the drive subsystem here, and override the getDriveTrainName function to return "swerve/vision"

2024-01-26 03:20 UTC, RobertTheBlair commented on src/main/java/frc/robot/subsystems/LimeVision/LimeLightSub.java
> +      System.out.println(getError());
put this on smart dashboard

2024-01-26 03:27 UTC, wilsomc commented on src/main/java/frc/robot/Constants.java
> +  public static final class LimeLightConstants {
will do in a different branch

2024-01-26 03:30 UTC, RobertTheBlair approved these changes

2024-01-26 03:32 UTC, merged